### ISSUE TITLE
Wrong pubchem ID for metabolite 3-methylhexane

### ISSUE THREAD

**Issue by riannefijten** [egonw/create-bridgedb-hmdb#11]
There's a wrong Pubchem ID for 3-methylhexane. The current pubchem ID in BridgeDB is: 11115931
[This refers to a compound with a double bond in the branch,](https://pubchem.ncbi.nlm.nih.gov/compound/11115931) instead of a methyl group. It should be [11507](https://pubchem.ncbi.nlm.nih.gov/compound/3-methylhexane#section=Top)

**Comment by egonw** [comment]
What's the Wikidata entry/URL?

**Comment by riannefijten** [comment]
[Q223103](https://www.wikidata.org/wiki/Q223103)

**Comment by egonw** [comment]
Fixed in the upcoming version:

    pubchem2wikidata.csv:http://www.wikidata.org/entity/Q223103,11507
